config/routes.rb
Rails.application.routes.draw do
  resources :categories

   root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true, uniqueness:true
	validates :description, presence:true, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end

	def show
		@category = Category.find(params[:id])
	end

	def edit
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
	end

	def create		
		@category = Category.new(name: params[:category][:name],description: params[:category][:description])
		if @category.save 
			redirect_to categories_path #redirecciona al listado
		else
			render :new
		end	
	end

	def update		
		@category = Category.find(params[:id])
		if @category.update(name: params[:category][:name], description: params[:category][:description])	
			redirect_to categories_path
		else
			render :edit
		end
	end
#acción destroy del método delete
	def destroy
		@category = Category.find(params[:id]) #necesita saber cual va a llevarse al carajo ;)
		@category.destroy

		redirect_to categories_path
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
	<% name ||= "Nueva" %>
	<h2><%= name%> Categoría </h2>
	<%= form_for (@category) do |f| %>
		<% if @category.errors.full_messages.length > 0 %>
			<div class="alert alert-dimissible alert-danger">
				<button type='button' class='close' data-dismiss='alert'>x</button>
				<% @category.errors.full_messages.each do |messages| %>
					<h5><%= messages %></h5>
				<%end%>
			</div>
		<%end%>
	<div>
		<%= f.text_field :name, placeholder: "Nombre", class:"form-control"%>
	</div>
	<div>
		<%= f.text_area :description, placeholder: "Escribe aqui la description", style: "height:250px", class:"form-control" %>
	</div>
	<div>
		<%= link_to "Regresar", categories_path, class:"btn btn-default"%>
		<%= f.submit "Guardar", class:"btn-btn-info"%>
	</div>
	<%end%>

app/views/categories/edit.html.erb
<div style='width: 80%; margin:0 auto;'>
	<%= render "form", name:"Editar" %>
</div>

app/views/categories/index.html.erb
<table class="table table-sstriped table-hover">
	<thead>
		<tr>
		<th>Nombre</th>
		<th>Descripción</th>
		<th width='250px' align='center'></th>
			<%= link_to "Nuevo", new_category_path(), class:'btn btn-default'%>
		</tr>
	</thead>
	<tbody>
		<% @categories.each do |category| %>
		<tr>
			<td><%= category.name %></td>
			<td><%= category.description %></td>
			<td>
				<%= link_to "Ver",category, class:'btn btn-primary' %>
				<%= link_to "Editar",edit_category_path(category), class:'btn btn-success' %>
				<%= link_to "Eliminar",category, method: :delete, class:'btn btn-danger' %>
			</td>
		</tr>
		<%end%>
	</tbody>
</table>

app/views/categories/new.html.erb
<div style='width: 80%; margin:0 auto;'>
	<%= render "form", name:"Nueva" %>
</div>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2> 
	<div>
		<%= @category.description %> 
	</div>
<div>
	<%= link_to "Regresar", categories_path, class:"btn btn-default" %>
	<%= link_to "Editar", edit_category_path(@category), class:"btn btn-info" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Categorias</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul>
    </div>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>